### PR TITLE
fix(deps): fix dependencies and update mjml example file to v4

### LINKED ISSUE #36: Gulp should be in devDependencies
Gulp is not needed as a dependency when running this plugin. Move it to devDependencies to avoid users having to install a new gulp when they install your package. This is also in accordance to item 14 in the [plugin guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md#guidelines).

### PR DESCRIPTION
**Pull request by eseliger**
I moved gulp to a `devDependency`, as per gulp plugin guideline. I also added the keyword `gulpplugin` so it can be found in the gulp plugin search 🙂 

The mjml test file was also in mjml v3 format, I migrated it to v4 as it is the version which is allowed in the semver range

Closes #36

### CODE REVIEW

**Comment by eseliger** [comment]
Hey together, I updated this pr to the latest master and this would still be nice to be merged, so this follows the gulp plugin guidelines!

**Comment by iRyusa** [comment]
Hi @eseliger 
Sorry about that one, can you just remove the package lock so we can merge it ? thanks !

**Comment by eseliger** [comment]
Hey @iRyusa the package-lock has only been modified and not added, and only relfects the changes to the package.json in this pr :)

**Comment by iRyusa** [comment]
Yep I know but we want to use yarn across our projects :D

**Comment by eseliger** [comment]
So shall I remove it completely? 🤔

**Comment by iRyusa** [comment]
Yep please !

**Comment by eseliger** [comment]
Done!

**Comment by eseliger** [comment]
hey, @iRyusa any updates how we can push this forward?

**Comment by iRyusa** [comment]
Forgot to merge it sorry 👍

**Comment by eseliger** [comment]
Thank you 🙂 let me know if you publish to npm!

**Pull request merged**
